/*-----------------------------------------------------------------------
 * @ file        : users.js
 * @ description : This file defines the user schema for mongodb.
 * @ author      :Anurag Gupta
 * @ date        : 27 April, 2017
 -----------------------------------------------------------------------*/


const Mongoose = require('mongoose');
const Schema = Mongoose.Schema;
const env = require('../env');
const mongooseSequence  = require('mongoose-sequence');
const Configs = require('../Configs');
const APP_CONSTANTS = Configs.CONSTS;
var retsPropertyRd_1_Schema = new Schema({
propertyAutoIncrement: { type: Number,unique: true,index:true,sparse:true},
 isFeatured: {type: Boolean, default: false},
 isDeleted: {type: Boolean, default: false},
 propertyImages:{type:Array,'default': []},
//allData:   Schema.Types.Mixed,
 //"images_downloded" : "1",
    agentId: {type: Schema.ObjectId, ref: 'user',index:true,sparse: true},
    createdAt: {type: Date, default: new Date()},
    updatedAt: {type: Date, default: new Date()},
    location: {
       'type': {type: String, enum: "Point", default: "Point"},//LineString //Polygon
       coordinates: [Number]
    },
    "l_listingid"   :  {type: Number},
    "l_displayid" : {type: String,trim: true, index: true,sparse:true},   //mlsnumber
    "lm_char1_36"   :  {type: String,trim: true, index: true}, //Prop Type
    "lm_int1_19"    :  {type: Number,trim: true, index: true}, //Total Baths
    "lm_int1_4"     :  {type: Number,trim: true, index: true}, //Total Bedrooms
    "l_area"        :  {type: String,trim: true, index: true},//area
    "l_askingprice" :  {type: Number,trim: true, index: true}, //price
    "lm_dec_14"     :  {type: Number,trim: true, index: true}, //Lot Sz (Hectares)
    "lm_dec_13"     :  {type: Number,trim: true, index: true}, //Lot Sz (Sq.Mtrs.)
    "lm_dec_12"     :  {type: Number,trim: true, index: true}, //Lot Sz (Acres)
    "lm_dec_11"     :  {type: Number,trim: true, index: true}, //Lot Sz (Sq.Ft.)
    "lm_char10_22"  :  {type: String,trim: true, index: true},//Dist to School/School Bus
    "lm_int1_8"     : {type: Number},
    "lfd_featuresincluded_55" : {type: String}, //Features Included
    "l_listingdate_unix": {type: Number}, // listing date in unix format
    "l_picturecount" : {type: Number},
    "l_updatedate" : {type: String}, //"2017-04-25 23:50:00",
    "l_listingdate" : {type: String}, //"2013-04-25",
    "lm_dec_16" :  {type: String}, //Gross Taxes
    "lm_int2_3" : {type: Number},//age
    "lm_int4_2" : {type: Number}, //  STRATA FEES
    "l_pricepersqft" : {type: Number}, //pricepersqft
    "lr_remarks22" : {type: String , default: ''},  //short description

    "l_zip" : {type: String},
    "l_state" : {type: String},
    "l_city" : {type: String},

    "lm_dec_7" : {type: Number,trim: true, index: true},//SQFT
    "lo1_organizationname" :  {type: String},
    "lo2_organizationname" : {type: String},
    "lm_int1_1" : {type: Number}, // No. Floor Levels
    "lm_char10_11" : {type: String}, //Type of Dwelling



    "lm_char10_12" : {type: String,trim: true, index: true},// Title to Land
    "l_remarks" : {type: String}, //Legal Description
    "lfd_amenities_56" : {type: String},
    "la2_email"     :  {type: String},
    "l_listagent1"  : {type: Number,index: true},
    "l_idxinclude"     : {type: String},
    "lv_vow_address"   :  {type: String},
    "lv_vow_include"   : {type: String},
    "lo3_webpage"      :  {type: String},
    "lo3_phonenumber1" : {type: String},
    "lo3_organizationname" : {type: String},
    "lo3_shortname"        : {type: String},
    "lo2_webpage"          : {type: String},
    "lo2_phonenumber1"     : {type: String},

    "lo2_shortname"        : {type: String},
    "lo1_webpage"          : {type: String},
    "lo1_phonenumber1"     : {type: String},

    "lo1_shortname" :  {type: String},
    "la3_char100_1" :  {type: String},
    "la3_webpage" :  {type: String},
    "la3_email" :  {type: String},
    "la3_phonenumber1" :  {type: String},
    "la3_loginname" : {type: String},
    "la2_char100_1" : {type: String},
    "la2_webpage" :  {type: String},
    "la2_phonenumber1" : {type: String},
    "la2_loginname" :  {type: String},
    "la1_char100_1" :  {type: String},
    "la1_webpage" :  {type: String},
    "la1_email" :  {type: String},
    "la1_phonenumber1" :  {type: String},
    "la1_loginname" :  {type: String},
    "lr_remarks33" :{type: String},
    "lfd_directionalexpfaces_59" : {type: String},
    "lfd_bylawrestrictions_58" :{type: String},
    "lfd_maintfeeincludes_57" : {type: String},


    "lfd_floorfinish_50" :{type: String},
    "lfd_fireplacefueledby_49" : {type: String},
    "lfd_fuelheating_48" :  {type: String},
    "lfd_outdoorarea_47" :  {type: String},
    "lfd_siteinfluences_46" :  {type: String},
    "lfd_parkingaccess_45" :  {type: String},
    "lfd_parking_44" :  {type: String},
    "lfd_roof_43" :  {type: String},
    "lfd_exteriorfinish_42" :  {type: String},
    "lfd_construction_41" :  {type: String},
    "lfd_directionalexprearyard_40" :  {type: String},
    "lfd_watersupply_39" :  {type: String},
    "lfd_servicesconnected_38" : {type: String},
    "lfd_basementarea_37" :  {type: String},
    "lfd_suite_36" :{type: String},
    "LFD_Suite_5" : {type: String},
    "LFD_MaintFeeIncludes_26":{type: String},
    "LFD_DirectionalExpFaces_28":{type: String},
    "LFD_DirectionalExpRearYard_9":{type: String},
    "LFD_ByLawRestrictions_27":{type: String},
    "lfd_renovations_35" :  {type: String},
    "lfd_styleofhome_32" :  {type: String},
    "vt_vtoururl" : "",
    "lm_dec_22" :  {type: String},
    "lm_char100_3" : {type: String}, //"CITY & MOUNTAIN",
    "lm_char100_1" : {type: String},
    "lm_char30_28" : {type: String},
    "lm_char30_5" : {type: String},
    "lm_char30_4" : {type: String},
    "lm_char30_3" : {type: String},
    "lm_char30_2" : {type: String},
    "lm_char10_70" : {type: String},
    "lm_char10_69" : {type: String},
    "lm_char10_68" : {type: String},
    "lm_char10_67" : {type: String},
    "lm_char10_66" : {type: String},
    "lm_char10_65" : {type: String},
    "lm_char10_64" : {type: String},
    "lm_char10_63" :{type: String},
    "lm_char10_62" : {type: String},
    "lm_char10_61" : {type: String},
    "lm_char10_60" : {type: String},
    "lm_char10_59" : {type: String},
    "lm_char10_58" : {type: String},
    "lm_char10_57" : {type: String},
    "lm_char10_56" : {type: String},
    "lm_char10_55" : {type: String},
    "lm_char10_54" : {type: String},
    "lm_char10_53" : {type: String},
    "lm_char10_52" : {type: String},
    "lm_char10_51" : {type: String},
    "lm_char10_50" : {type: String},
    "lm_char10_49" : {type: String},
    "lm_char10_48" : {type: String},
    "lm_char10_47" : {type: String},
    "lm_char10_46" : {type: String},
    "lm_char10_45" : {type: String},
    "lm_char10_44" : {type: String},
    "lm_char10_43" : {type: String},
    "lm_char10_42" : {type: String},
    "lm_char10_41" : {type: String},
    "lm_char10_40" : {type: String},
    "lm_char10_39" : {type: String},
    "lm_char10_38" : {type: String},
    "lm_char10_37" : {type: String},
    "lm_char10_36" : {type: String},
    "lm_char10_35" : {type: String},
    "lm_char10_34" : {type: String},
    "lm_char10_33" : {type: String},
    "lm_char10_32" : {type: String},
    "lm_char10_31" : {type: String},
    "lm_char5_60" : {type: String},
    "lm_char5_59" : {type: String},
    "lm_char5_58" : {type: String},
    "lm_char5_57" : {type: String},
    "lm_char5_56" : {type: String},
    "lm_char5_55" : {type: String},
    "lm_char5_54" : {type: String},
    "lm_char5_53" : {type: String},
    "lm_char5_52" : {type: String},
    "lm_char5_51" : {type: String},
    "lm_char5_50" : {type: String},
    "lm_char5_49" : {type: String},
    "lm_char5_48" : {type: String},
    "lm_char5_47" : {type: String},
    "lm_char5_46" : {type: String},
    "lm_char5_45" : {type: String},
    "lm_char5_44" : {type: String},
    "lm_char5_43" : {type: String},
    "lm_char5_42" : {type: String},
    "lm_char5_41" : {type: String},
    "lm_char5_40" : {type: String},
    "lm_char5_39" : {type: String},
    "lm_char5_38" : {type: String},
    "lm_char5_37" : {type: String},
    "lm_char5_36" : {type: String},
    "lm_char5_35" : {type: String},
    "lm_char5_34" : {type: String},
    "lm_char5_33" : {type: String},
    "lm_char5_32" : {type: String},
    "lm_char5_31" : {type: String},
    "lm_char5_30" : {type: String},
    "lm_char5_29" : {type: String},
    "lm_char5_28" : {type: String},
    "lm_char5_27" : {type: String},
    "lm_char5_26" : {type: String},
    "lm_char5_25" : {type: String},
    "lm_char5_24" : {type: String},
    "lm_char5_23" : {type: String},
    "lm_char5_22" : {type: String},
    "lm_char5_21" : {type: String},
    "lm_char5_20" :{type: String},
    "lm_char5_19" :{type: String},
    "lm_char5_18" : {type: String},
    "lm_char5_17" : {type: String},
    "lm_char5_16" : {type: String},
    "lm_char5_15" : {type: String},
    "lm_char5_14" : {type: String},
    "lm_char5_13" : {type: String},
    "lm_char5_12" : {type: String},
    "lm_char5_11" : {type: String},
    "lm_char5_10" :{type: String},
    "lm_char5_9" : {type: String},
    "lm_char5_8" : {type: String},
    "lm_char5_7" : {type: String},
    "lm_char5_6" : {type: String},
    "lm_char5_5" : {type: String},
    "lm_char5_4" : {type: String},
    "lm_char5_3" : {type: String},
    "lm_dec_9" : {type: String},
    "lm_dec_8" : {type: String},
    "lm_dec_6" : {type: String},
    "lm_dec_5" : {type: String},
    "lm_dec_4" : {type: String},
    "lm_dec_3" : {type: String},
    "lm_dec_2" : {type: String},
    "lm_dec_1" : {type: String},
    "lm_int4_1" :{type: Number},
    "lm_int2_8" : {type: Number},
    "lm_int2_7" : {type: Number},
    "lm_int2_6" : {type: Number},
    "lm_int2_5" : {type: Number},
    "lm_int2_4" : {type: Number},
    "lm_int2_2" : {type: Number},
    "lm_int1_20" : {type: Number},
    "lm_int1_18" :{type: Number},
    "lm_int1_17" :{type: Number},
    "lm_int1_16" : {type: Number},
    "lm_int1_15" : {type: Number},
    "lm_int1_14" : {type: Number},
    "lm_int1_13" : {type: Number},
    "lm_int1_12" : {type: Number},
    "lm_int1_11" : {type: Number},
    "lm_int1_10" : {type: Number},
    "lm_int1_9" : {type: Number},
    "lm_int1_7" : {type: Number},
    "lm_int1_6" : {type: Number},
    "lm_int1_5" : {type: Number},
    "lm_int1_3" : {type: Number},
    "lm_int1_2" : {type: Number},
    "lm_int1_1" : {type: Number},
    "lm_char50_5" : {type: String},
    "lm_char25_30" : {type: String},
    "lm_char25_27" : {type: String},
    "lm_char25_23" : {type: String},
    "lm_char25_22" : {type: String},
    "lm_char25_21" :{type: String},
    "lm_char25_20" : {type: String},
    "lm_char25_19" :  {type: String},
    "lm_char25_18" :  {type: String},
    "lm_char25_17" :  {type: String},
    "lm_char25_16" :  {type: String},
    "lm_char25_15" :  {type: String},
    "lm_char25_14" :  {type: String},
    "lm_char25_13" : {type: String},
    "lm_char25_12" :  {type: String},
    "lm_char25_11" :  {type: String},
    "lm_char25_10" :  {type: String},
    "lm_char25_9" :  {type: String},
    "lm_char25_8" :  {type: String},
    "lm_char25_7" :  {type: String},
    "lm_char25_6" : {type: String},
    "lm_char25_5" : {type: String},
    "lm_char25_4" : {type: String},
    "lm_char10_30" : {type: String},
    "lm_char10_29" :{type: String},
    "lm_char10_28" : {type: String},
    "lm_char10_27" : {type: String},
    "lm_char10_26" : {type: String},
    "lm_char10_25" : {type: String},
    "lm_char10_24" : {type: String},
    "lm_char10_23" : {type: String},
    "lm_char10_21" : {type: String},
    "lm_char10_19" : {type: String},
    "lm_char10_18" : {type: String},
    "lm_char10_17" : {type: String},
    "lm_char10_16" :{type: String},
    "lm_char10_13" : {type: String},
    "lm_char10_6" : {type: String},
    "lm_char10_5" : {type: String},
    "lm_char10_3" : {type: String},
    "lm_char1_16" : {type: String},
    "lm_char1_15" : {type: String},
    "lm_char1_14" : {type: String},
    "lm_char1_13" : {type: String},
    "lm_char1_10" : {type: String},
    "lm_char1_9" : {type: String},
    "lm_char1_8" : {type: String},
    "lm_char1_7" : {type: String},
    "lm_char1_6" : {type: String},
    "lm_char1_5" : {type: String},
    "lm_char1_4" : {type: String},
    "lm_char1_3" : {type: String},
    "lm_char1_2" : {type: String},
    "lm_char1_1" : {type: String},
    "l_status" : {type: String},
    "l_address" : {type: String},
    "l_streetdesignationid" : {type: String},
    "l_addressunit": {type: String},
    "l_addressnumberlow" :{type: String},
    "l_last_photo_updt" : {type: String}, //"2015-07-02 10:52:00",
    "l_listagent3" : {type: Number},
    "l_listoffice2" :{type: Number},
    "l_listagent2" :{type: Number},
    "l_listoffice1" :{type: Number},
    "l_addressstreet" : {type: String},
    "l_addressdirection" :{type: String},
    "l_addressnumber" : {type: String}, //"8288",
    "images_count" : { type : Number},
    "additional_data" : [Schema.Types.Mixed]
} ,{strict: false});
//Mongoose.set('debug', true); // console mongo queries
retsPropertyRd_1_Schema.plugin(mongooseSequence, { inc_field: 'propertyAutoIncrement' });
retsPropertyRd_1_Schema.index( { location : "2dsphere" })
//UserSchema.index({ name: "text" }, { default_language: "none" });
var retsPropertyRd_1 = Mongoose.model('retspropertyrd_1', retsPropertyRd_1_Schema);
module.exports = retsPropertyRd_1;
